"""empty message

Revision ID: 42a21f5ecca8
Revises: 
Create Date: 2023-05-04 21:57:14.846539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a21f5ecca8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('left_number', sa.Float(), nullable=False),
    sa.Column('right_number', sa.Float(), nullable=False),
    sa.Column('execution_string', sa.Text(), nullable=False),
    sa.Column('result', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_history_id'), 'operation_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_history_id'), table_name='operation_history')
    op.drop_table('operation_history')
    # ### end Alembic commands ###
